name: "01. Execução Manual"

on:
  workflow_dispatch:

jobs:
  inspection:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Configurando Node.js
        uses: actions/setup-node@v2
        with:
          node-version: "18"

      - name: Instalando Dependências
        run: npm install

      - name: Inspecionando Projeto (Lint)
        run: npm run lint:check

  e2e-tests:
    runs-on: ubuntu-latest
    needs: inspection

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Configurando Node.js
        uses: actions/setup-node@v2
        with:
          node-version: "18"

      - name: Instalando Dependências
        run: npm install

      - name: Testes E2E (end to end)
        run: npm run test:e2e
